export abstract class CommonConstants {
  public static Selectors = {
    MenuTicketSystem: {
      MENU_FORM: "#menuForm\\:j_idt18",
      RESELLER_LIST: "#menuForm\\:tarChanger_input",
    },
    Navigation: {
      CREATE_TICKET_CLOSE_TOP: "#createSearchForm\\:closeButton1",
      CREATE_TICKET_CLOSE_BOTTON: "#createSearchForm\\:closeButton2",
      CREATE_TICKET_SAVE_TOP: "#createSearchForm\\:saveButton1",
      CREATE_TICKET_SAVE_UP: "#createSearchForm\\:saveButton",
      CREATE_TICKET_SAVE_BOTTON: "#createSearchForm\\:saveButton2",
      NEXT_BUTTON: "#createDisplayCustomerForm\\:nextButtonUp",
      PREVIOUS_BUTTON: "#editForm\\:homeMenu2",
    },
    Portstatus: {
      CAP_INVENTORY_ID: "input#inventoryForm\\:invId",
      SEARCH_CAP_KUNDENNR: "input#inventoryForm\\:invButton",
      RESULT_DIAGNOSE: "#portStatusCenterResult",
    },
    SearchTicketForm: {
      TICKET_SUCHE_BUTTON: "#ticketSearchBox_toggler> .ui-icon",
      TICKET_ID: "#ticketSearchForm\\:ticketId",
      MEMBER_TICKET_ID: "#ticketSearchForm\\:memberTicketId",
      SUBSCRIBER_ID: "#ticketSearchForm\\:subscriberId",
      CAP_INVENTORY_ID: "#ticketSearchForm\\:capInventoryId",
      KUNDENNUMMER_CAP_RESELLER: "#ticketSearchForm\\:customerNumber",
      KUNDEN_VORNAME: "#ticketSearchForm\\:customerFirstName",
      KUNDEN_NACHNAME: "#ticketSearchForm\\:customerLastName",
      STATUS: "#ticketSearchForm\\:ticketStatus_input",
      LAST_UPDATE: "#ticketSearchForm\\:lastUpdated_input",
      TICKET_SUCHE_CONTAINER: "#ticketSearchForm",
      ERGEBNIS_LISTE: "#main-content",
    },
    DetailTicket: {
      PLUS_INFO_BUTTON:
        "#ticketsForm\\:ticketRepeater\\:0\\:hierachyDetails_toggler> .ui-icon",
    },
    EditTicketForm: {
      FIRST_ROW_LIST_TICKET: ".pad_l> tbody> tr:eq(1)",
      BUTTON_EDIT_TICKET: ".icon_edit",
      PROBLEM_BESCHREIBUNG: "#editForm\\:ticketProblemInput",
      STATUS_CONTAINER: ":nth-of-type(5) > .hl_light",
      STATUS_CONTAINER_TAL: ":nth-of-type(6) > .hl_light",
      REFRESH_BUTTON: "#editForm\\:refreshButton1",
      Status_edit: {
        VERANTWORTLICH: "verantwortlich",
        WEITERGELEITET: "weitergeleitet",
        GELOEST: "gelöst",
        ABGEBROCHEN: "abgebrochen",
        ANGEHALTEN: "angehalten",
        REKLAMIERT: "wieder eröffnet",
        CLOSE: "geschlossen",
      },
      WEITERLEITUNG_CONTAINER_SUP: ":nth-child(7) > .hl_mid",
      WEITERLEITUNG_CONTAINER_SUP_TAL: ":nth-child(8) > .hl_mid",
      WEITERLEITUNG_CONTAINER_RES: ":nth-child(6) > .hl_mid",
      WEITERLEITUNG_CONTAINER_RES_TAL: ":nth-child(7) > .hl_mid",
      Weiterleitung_ticket: {
        SPEICHERN: "Speichern (ggf. Auto-Synchronisation)",
        WEITERLEITUNG_3L: "Weiterleitung zum vitroconnect 3rd Level",
      },
      BUTTON_VALID_FORM: "#editForm\\:validateButton1",
      BUTTON_SAVE_FORM: "#editForm\\:saveButton1",
      BUTTON_SAVE_FORM2: "input[name='editForm:saveButton1']",
      TICKET_INFO_LINE: ".ticketInfoLine",
      BESCHREIBUNG_BOX: "#descriptionBox> .catLvl5",
      BESCHREIBUNG_BOX2: "#descriptionBox> .catLvl3",
      BESCHREIBUNG_BOX3: "#descriptionBox> .catLvl2",
      BESCHREIBUNG_BOX_FAX: "#descriptionBox> .catLvl1",
      EDIT_CENTER_CONTAINER: "#editCenter",
      BUTTON_PLUS: ".ui-icon",
      TICKET_NAME: ":nth-child(1)> .hl_light> .limitTextInput> .fitHoriz",
      Status: {
        OPENE: "Open",
        VERANTWORTLICH: "verantwortlich",
        WEITERGELEITET: "weitergeleitet",
        RESOLVED: "Resolved",
        GELOEST: "gelöst",
        CLOSE: "Closed",
        GESCHLOSSEN: "geschlossen",
        CANCEL: "Cancelled",
        ABBRUCH: "abgebrochen",
        EROEFFNET: "eröffnet",
      },
    },
  };
}
